/*
 * @nevware21/ts-utils
 * https://github.com/nevware21/ts-utils
 *
 * Copyright (c) 2022-2026 NevWare21 Solutions LLC
 * Licensed under the MIT license.
 */

"use strict";

/**
 * Post-processing script to add TypeScript lib reference directives to the bundled
 * declaration file generated by api-extractor.
 *
 * The api-extractor tool strips `/// <reference lib="..." />` directives from the
 * bundled output. These directives are required so that consumers using ES5-only lib
 * settings in their tsconfig (e.g. `"lib": ["ES5", "DOM"]`) can compile code that
 * references the package's type declarations without encountering "Cannot find name"
 * errors for ES2015 built-ins such as Symbol, Iterator, Iterable, etc.
 */

var fs = require("fs");
var path = require("path");

var bundledDtsFile = path.resolve(__dirname, "../dist/types/ts-utils.d.ts");
var referenceDirective = "/// <reference lib=\"es2015\" />";

if (!fs.existsSync(bundledDtsFile)) {
    console.error("ERROR: Bundled d.ts file not found: " + bundledDtsFile);
    process.exit(1);
}

var content = fs.readFileSync(bundledDtsFile, "utf8");
var newLine = content.indexOf("\r\n") !== -1 ? "\r\n" : "\n";

if (content.indexOf(referenceDirective) === -1) {
    fs.writeFileSync(bundledDtsFile, referenceDirective + newLine + content, "utf8");
    console.log("Added '" + referenceDirective + "' to " + path.relative(process.cwd(), bundledDtsFile));
} else {
    console.log("Reference directive already present in " + path.relative(process.cwd(), bundledDtsFile));
}
