# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "NodeCI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096    

    strategy:
      matrix:
        node-version: [ 12, 14, 16, 18 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm install
    - name: Build
      run: npm run build --verbose
      timeout-minutes: 10
    - name: Unit tests
      run: npm run test --verbose
    - name: Report Coverage
      run: npm run codecov
